[package]
name = "telegram_files_server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.210"
serde_json = "1.0.128"

axum = { version = "0.7.7", features = ["multipart"] }
axum_typed_multipart = "0.13.0"

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
tower-http = { version = "0.6.1", features = ["trace"] }
sentry-tracing = "0.34.0"

tokio = { version = "1.40.0", features = [ "full" ] }
tokio-util = { version = "0.7.12", features = [ "full" ] }
axum-prometheus = "0.7.0"

futures = "0.3.30"

once_cell = "1.20.1"
teloxide = "0.13.0"

sentry = "0.34.0"

dotenvy = "0.15.0"

reqwest = { version = "0.11.27", features = [
    "json",
    "stream",
    "multipart",
], default-features = false }
moka = { version = "0.12.8", features = ["future"] }
