[package]
name = "telegram_files_server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.200"
serde_json = "1.0.116"

axum = { version = "0.7.5", features = ["multipart"] }
axum_typed_multipart = "0.11.1"

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
tower-http = { version = "0.5.2", features = ["trace"] }

tokio = "1.37.0"
tokio-util = { version = "0.7.11", features = [ "full" ] } 
axum-prometheus = "0.6.1"

futures = "0.3.30"

once_cell = "1.19.0"
teloxide = "0.12.2"

sentry = "0.32.3"

dotenv = "0.15.0"

reqwest = { version = "0.11.10", features = [
    "json",
    "stream",
    "multipart",
], default-features = false }
moka = { version = "0.12.7", features = ["future"] }
