[package]
name = "telegram_files_server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.216"
serde_json = "1.0.134"

axum = { version = "0.7.9", features = ["multipart"] }
axum_typed_multipart = "0.14.0"

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"]}
tower-http = { version = "0.6.2", features = ["trace"] }
sentry-tracing = "0.35.0"

tokio = { version = "1.42.0", features = [ "full" ] }
tokio-util = { version = "0.7.13", features = [ "full" ] }
axum-prometheus = "0.7.0"

futures = "0.3.31"

once_cell = "1.20.2"
teloxide = "0.13.0"

sentry = "0.35.0"

dotenvy = "0.15.7"

reqwest = { version = "0.11.27", features = [
    "json",
    "stream",
    "multipart",
], default-features = false }
moka = { version = "0.12.8", features = ["future"] }
