[tool.poetry]
name = "fastapi_file_server"
version = "0.1.0"
description = ""
authors = ["Kurbanov Bulat <kurbanovbul@gmail.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.88.0"
uvicorn = {extras = ["standart"], version = "^0.20.0"}
ormar = {extras = ["postgresql"], version = "^0.12.0"}
alembic = "^1.9.1"
pydantic = {extras = ["dotenv"], version = "^1.10.2"}
python-multipart = "^0.0.5"
httpx = "^0.23.1"
telethon = "^1.26.1"
prometheus-fastapi-instrumentator = "^5.9.1"
uvloop = "^0.17.0"
gunicorn = "^20.1.0"
orjson = "^3.8.3"
sentry-sdk = "^1.12.1"
greenlet = "^2.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
mypy = "^0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.vscode
  | \venv
  | alembic
)/
'''

[tool.flake8]
ignore = [
    # Whitespace before ':' ( https://www.flake8rules.com/rules/E203.html )
    "E203"
]
max-line-length=88
max-complexity = 15
select = "B,C,E,F,W,T4,B9"
exclude = [
    # No need to traverse our git directory
    ".git",
    # There's no value in checking cache directories
    "__pycache__",
    # The conf file is mostly autogenerated, ignore it
    "fastapi_file_server/app/alembic/*",
    # The old directory contains Flake8 2.0
]

[tool.isort]
profile = "black"
only_sections = true
force_sort_within_sections = true
lines_after_imports = 2
lexicographical = true
sections = ["FUTURE", "STDLIB", "BASEFRAMEWORK", "FRAMEWORKEXT", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_baseframework = ["fastapi",]
known_frameworkext = ["starlette",]
src_paths = ["fastapi_file_server"]
