[tool.poetry]
name = "fastapi_file_server"
version = "0.1.0"
description = ""
authors = ["Kurbanov Bulat <kurbanovbul@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0.post1"}
pydantic = "^2.5.1"
python-multipart = "^0.0.6"
telethon = "^1.32.1"
prometheus-fastapi-instrumentator = "^6.1.0"
uvloop = "^0.19.0"
orjson = "^3.9.10"
sentry-sdk = "^1.36.0"
pydantic-settings = "^2.1.0"
typing-extensions = "^4.8.0"
httptools = "^0.6.1"
pyyaml = "^6.0.1"
certifi = "^2023.11.17"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
mypy = "^0.991"
pre-commit = "^2.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.vscode
  | \venv
  | alembic
)/
'''

[tool.ruff]
fix = true
target-version = "py311"
src = ["fastapi_file_server"]
line-length=88
ignore = []
select = ["B", "C", "E", "F", "W", "B9", "I001"]
exclude = [
    # No need to traverse our git directory
    ".git",
    # There's no value in checking cache directories
    "__pycache__",
    # The conf file is mostly autogenerated, ignore it
    "fastapi_file_server/app/alembic",
]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.File", "fastapi.Form", "fastapi.Security"]

[tool.ruff.mccabe]
max-complexity = 15

[tool.ruff.isort]
known-first-party = ["core", "app"]
force-sort-within-sections = true
force-wrap-aliases = true
section-order = ["future", "standard-library", "base_framework", "framework_ext", "third-party", "first-party", "local-folder"]
lines-after-imports = 2

[tool.ruff.isort.sections]
base_framework = ["fastapi",]
framework_ext = ["starlette"]

[tool.ruff.pyupgrade]
keep-runtime-typing = true
