[tool.poetry]
name = "fastapi_file_server"
version = "0.1.0"
description = ""
authors = ["Kurbanov Bulat <kurbanovbul@gmail.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.68.1"
uvicorn = {extras = ["standart"], version = "^0.15.0"}
ormar = "^0.10.19"
alembic = "^1.7.3"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}
asyncpg = "^0.24.0"
psycopg2 = "^2.9.1"
python-multipart = "^0.0.5"
telegram-files-storage = {extras = ["all"], version = "^1.1.1"}
httpx = "^0.22.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.vscode
  | \venv
  | alembic
)/
'''

[tool.flake8]
ignore = [
    # Whitespace before ':' ( https://www.flake8rules.com/rules/E203.html )
    "E203"
]
max-line-length=88
max-complexity = 15
select = "B,C,E,F,W,T4,B9"
exclude = [
    # No need to traverse our git directory
    ".git",
    # There's no value in checking cache directories
    "__pycache__",
    # The conf file is mostly autogenerated, ignore it
    "fastapi_file_server/app/alembic/*",
    # The old directory contains Flake8 2.0
]

[tool.isort]
profile = "black"
only_sections = true
force_sort_within_sections = true
lines_after_imports = 2
lexicographical = true
sections = ["FUTURE", "STDLIB", "BASEFRAMEWORK", "FRAMEWORKEXT", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_baseframework = ["fastapi",]
known_frameworkext = ["starlette",]
src_paths = ["fastapi_file_server"]
